/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/_services'
import { Route as ContactRouteImport } from './routes/_contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesUpcomingeventsRouteImport } from './routes/_services/upcomingevents'
import { Route as ServicesOurservicesRouteImport } from './routes/_services/ourservices'
import { Route as ServicesClothingRouteImport } from './routes/_services/clothing'
import { Route as ContactGetinvolvedRouteImport } from './routes/_contact/getinvolved'
import { Route as ContactContactusRouteImport } from './routes/_contact/contactus'

const ServicesRoute = ServicesRouteImport.update({
  id: '/_services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/_contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUpcomingeventsRoute = ServicesUpcomingeventsRouteImport.update({
  id: '/upcomingevents',
  path: '/upcomingevents',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesOurservicesRoute = ServicesOurservicesRouteImport.update({
  id: '/ourservices',
  path: '/ourservices',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesClothingRoute = ServicesClothingRouteImport.update({
  id: '/clothing',
  path: '/clothing',
  getParentRoute: () => ServicesRoute,
} as any)
const ContactGetinvolvedRoute = ContactGetinvolvedRouteImport.update({
  id: '/getinvolved',
  path: '/getinvolved',
  getParentRoute: () => ContactRoute,
} as any)
const ContactContactusRoute = ContactContactusRouteImport.update({
  id: '/contactus',
  path: '/contactus',
  getParentRoute: () => ContactRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contactus': typeof ContactContactusRoute
  '/getinvolved': typeof ContactGetinvolvedRoute
  '/clothing': typeof ServicesClothingRoute
  '/ourservices': typeof ServicesOurservicesRoute
  '/upcomingevents': typeof ServicesUpcomingeventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contactus': typeof ContactContactusRoute
  '/getinvolved': typeof ContactGetinvolvedRoute
  '/clothing': typeof ServicesClothingRoute
  '/ourservices': typeof ServicesOurservicesRoute
  '/upcomingevents': typeof ServicesUpcomingeventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_contact': typeof ContactRouteWithChildren
  '/_services': typeof ServicesRouteWithChildren
  '/_contact/contactus': typeof ContactContactusRoute
  '/_contact/getinvolved': typeof ContactGetinvolvedRoute
  '/_services/clothing': typeof ServicesClothingRoute
  '/_services/ourservices': typeof ServicesOurservicesRoute
  '/_services/upcomingevents': typeof ServicesUpcomingeventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contactus'
    | '/getinvolved'
    | '/clothing'
    | '/ourservices'
    | '/upcomingevents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contactus'
    | '/getinvolved'
    | '/clothing'
    | '/ourservices'
    | '/upcomingevents'
  id:
    | '__root__'
    | '/'
    | '/_contact'
    | '/_services'
    | '/_contact/contactus'
    | '/_contact/getinvolved'
    | '/_services/clothing'
    | '/_services/ourservices'
    | '/_services/upcomingevents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_services': {
      id: '/_services'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_contact': {
      id: '/_contact'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_services/upcomingevents': {
      id: '/_services/upcomingevents'
      path: '/upcomingevents'
      fullPath: '/upcomingevents'
      preLoaderRoute: typeof ServicesUpcomingeventsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_services/ourservices': {
      id: '/_services/ourservices'
      path: '/ourservices'
      fullPath: '/ourservices'
      preLoaderRoute: typeof ServicesOurservicesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_services/clothing': {
      id: '/_services/clothing'
      path: '/clothing'
      fullPath: '/clothing'
      preLoaderRoute: typeof ServicesClothingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_contact/getinvolved': {
      id: '/_contact/getinvolved'
      path: '/getinvolved'
      fullPath: '/getinvolved'
      preLoaderRoute: typeof ContactGetinvolvedRouteImport
      parentRoute: typeof ContactRoute
    }
    '/_contact/contactus': {
      id: '/_contact/contactus'
      path: '/contactus'
      fullPath: '/contactus'
      preLoaderRoute: typeof ContactContactusRouteImport
      parentRoute: typeof ContactRoute
    }
  }
}

interface ContactRouteChildren {
  ContactContactusRoute: typeof ContactContactusRoute
  ContactGetinvolvedRoute: typeof ContactGetinvolvedRoute
}

const ContactRouteChildren: ContactRouteChildren = {
  ContactContactusRoute: ContactContactusRoute,
  ContactGetinvolvedRoute: ContactGetinvolvedRoute,
}

const ContactRouteWithChildren =
  ContactRoute._addFileChildren(ContactRouteChildren)

interface ServicesRouteChildren {
  ServicesClothingRoute: typeof ServicesClothingRoute
  ServicesOurservicesRoute: typeof ServicesOurservicesRoute
  ServicesUpcomingeventsRoute: typeof ServicesUpcomingeventsRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesClothingRoute: ServicesClothingRoute,
  ServicesOurservicesRoute: ServicesOurservicesRoute,
  ServicesUpcomingeventsRoute: ServicesUpcomingeventsRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
